# Generated by Django 5.1.1 on 2024-10-25 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlybites_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('surname', models.CharField(max_length=75)),
                ('birthdate', models.DateTimeField()),
                ('mail', models.CharField(max_length=75)),
                ('telephone', models.CharField(max_length=75)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='valoration',
            name='user',
        ),
        migrations.AddField(
            model_name='address',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onlybites_web.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onlybites_web.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valoration',
            name='profile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='onlybites_web.profile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
