# Generated by Django 5.1.1 on 2024-11-04 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlybites_web', '0008_remove_cart_state_alter_cart_quantity_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onlybites_web.address'),
            preserve_default=False,
        ),
    ]
