# Generated by Django 5.1.1 on 2024-11-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlybites_web', '0009_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergen',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='allergen',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='allergen',
            name='description_es',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allergen',
            name='description_eu',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allergen',
            name='name_es',
            field=models.CharField(default=1, max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allergen',
            name='name_eu',
            field=models.CharField(default=1, max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description_es',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description_eu',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name_es',
            field=models.CharField(default=1, max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name_eu',
            field=models.CharField(default=1, max_length=75),
            preserve_default=False,
        ),
    ]
